@host=127.0.0.1
@port=5000
@url=http://{{host}}:{{port}}

GET {{url}}/json HTTP/1.1
Content-Type: application/json

{
    "task": "todo list",
    "isCompleted": true
}

###

GET {{url}}/form HTTP/1.1
Content-Type: application/x-www-form-urlencoded

task=todo
&isCompleted=true

###

POST {{url}}/iform HTTP/1.1
Content-Type: multipart/form-data; boundary=X-BOUNDARY
--X-BOUNDARY
Content-Disposition: form-data; name="task"
todo
--X-BOUNDARY
Content-Disposition: form-data; name="isCompleted"
true
--X-BOUNDARY--